CREATE DATABASE QLVeMayBay
USE QLVeMayBay

SET DATEFORMAT mdy


-----------------------------------------
----------- Tao Bang-------------
CREATE TABLE KHACHHANG
(
	MAKH CHAR(5) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	TUOI INT,
	GIOITINH BIT,
	CMND CHAR(15),
	DIACHI NVARCHAR(50),
	SDT CHAR(15),
)
CREATE TABLE HANGHK
(
	MAHHK CHAR(5) PRIMARY KEY,
	TENHHK NVARCHAR(30),
)
CREATE TABLE SANBAY
(
	MASB CHAR(5) PRIMARY KEY,
	TENSANBAY NVARCHAR(40),
)
CREATE TABLE CHUYENBAY
(
	MACB CHAR(5) PRIMARY KEY,
	MASBDI CHAR(5),
	MASBDEN CHAR(5),
	MAHHK CHAR(5),	
	THOIGIANKHOIHANH SMALLDATETIME,
	THOIGIANDEN SMALLDATETIME,
	SOGHEHANG1 INT,
	SOGHEHANG2 INT,
	GIAVE INT
)

CREATE TABLE HANGVE
(
	MAHV CHAR(5) PRIMARY KEY,
	TENHANGVE NVARCHAR(20),
)
CREATE TABLE TINHTRANG
(
	MATT CHAR(5) PRIMARY KEY,
	TENTINHTRANG NVARCHAR(10),
)
CREATE TABLE VE
(
	MAVE CHAR(5) PRIMARY KEY,
	MACB CHAR(5),
	MAHHK CHAR(5),
	MAHV CHAR(5),
	GIATIEN INT,	
	MATT CHAR(5),
)

CREATE TABLE CHITIETCB
(
	MACB CHAR(5) PRIMARY KEY,
	MASBTG CHAR(5),
	THOIGIANDUNG INT,
	GHICHU NVARCHAR(20),
)
CREATE TABLE PHIEUDATMUA
(	
	MAVE CHAR(5),
	MAKH CHAR(5),
	THOIGIANDAT SMALLDATETIME,
	DATHANHTOAN BIT
	PRIMARY KEY (MAVE, MAKH)
)
CREATE TABLE THAMSO
(
	MATS CHAR(5),
	NGAYAPDUNG SMALLDATETIME,
	TENTS NVARCHAR(20),
	GIATRI INT,
)

<<<<<<< HEAD


-------------------------------------------
------------ Insert Du lieu -----------
Insert into HANGVE Values
('HV001', N'Vé hạng 1'),
('HV002', N'Vé hạng 2')

Insert into CHITIETCB Values
('CB01', 'SB02', 15, Null),
('CB02', 'SB01', 20, Null),
('CB03', 'SB02', 35, Null)

Insert into HANGHK Values
('HHK01', 'VietNam Airline'),
('HHK02', 'Jetstar'),
('HHK03','VASCO'),
('HHK04','Jetstar Pacific Airlines')

Insert into CHUYENBAY Values
('CB01', 'SB01', 'SB02', 'HHK01', '3/5/2018 09:00:00', '5/3/2018 12:00:00', 10, 10, 100000),
('CB02', 'SB03', 'SB02', 'HHK02', '4/5/2018 13:15:00', '5/4/2018 16:30:00',20, 20, 200000),
('CB03', 'SB01', 'SB03', 'HHK01', '5/5/2018 03:00:00', '5/5/2018 08:10:00', 15, 15, 150000)

Insert into KHACHHANG Values
('KH01', N'Nguyễn Văn A', 15, 1, '2778194257', 'TPHCM', '0987234612'),
('KH02', N'Trần Thị B', 17, 0, '273278135', N'Bình Dương', '0917246182'),
('KH03', N'Lê Văn C', 16, 1, '253261268', N'Đồng Nai', '0982612341'),
('KH05', N'Võ Thanh Minh', 35, 1, '215467289', 'BR-VT', '0643265172')

Insert into SANBAY Values
('SB01', N'Đà Nẵng'),
('SB02', N'HCM'),
('SB03', N'Hà Nội')

Insert into TINHTRANG Values
('TT000', N'Còn trống'),
('TT001', N'Đã bán'),
('TT002', N'Đã đặt')

Insert into VE Values
('VE101', 'CB01', 'HHK01', 'HV001', 1005000, 'TT000'),
('VE102', 'CB01', 'HHK01', 'HV002', 1000000, 'TT000'),
('VE103', 'CB01', 'HHK01', 'HV001', 1005000, 'TT000'),
('VE201', 'CB02', 'HHK03', 'HV001', 2100000, 'TT000'),
('VE202', 'CB02', 'HHK03', 'HV001', 2100000, 'TT000'),
('VE203', 'CB02', 'HHK03', 'HV002', 2000000, 'TT000'),  
('VE301', 'CB03', 'HHK04', 'HV002', 1500000, 'TT001'),
('VE302', 'CB03', 'HHK04', 'HV001', 1575000, 'TT002')

Insert into PHIEUDATMUA Values
('VE301', 'KH01', '5/1/2018 08:00:00', 1),
('VE302', 'KH03', '4/28/2018 23:15:05', 0)

--------------------------------------------
----------- Tao Procedure----------

---------- Procedure Khach --------
=======
insert into TINHTRANG values('TT000', N'CÒN TRỐNG');
insert into TINHTRANG values('TT001', N'ĐÃ BÁN');
insert into TINHTRANG values('TT002', N'ĐÃ ĐẶT');

insert into HANGVE values('HV001', N'Vé Hạng 1')
insert into HANGVE values('HV002', N'Vé Hạng 2')

insert into  SANBAY values('SB001', N'Đà Nẵng')
insert into  SANBAY values('SB002', N'Nội Bài')
insert into  SANBAY values('SB003', N'Tân Sơn Nhất')
insert into  SANBAY values('SB004', N'Phú Quốc')
insert into  SANBAY values('SB005', N'Vinh')
insert into  SANBAY values('SB006', N'Lai')
insert into  SANBAY values('SB007', N'Hòa')
insert into  SANBAY values('SB008', N'Đồng Hới')
insert into  SANBAY values('SB009', N'Điện Biên Phủ')
insert into  SANBAY values('SB010', N'Cà Mau')

insert into HANGHK values('HHK01','Vietnam Airlines')
insert into HANGHK values('HHK02','VietJetAir')
insert into HANGHK values('HHK03','VASCO')
insert into HANGHK values('HHK04','Jetstar Pacific Airlines')

insert into CHUYENBAY values ('CB001','SB001','SB009','HHK01','5/15/2018','5/15/2018','50','50',1000000)
insert into CHUYENBAY values ('CB002','SB002','SB010','HHK03','5/16/2018','5/16/2018','60','60',2000000)
insert into CHUYENBAY values ('CB003','SB003','SB007','HHK04','12/5/2018','12/5/2018','40','40',1500000)

insert into VE values('VE101','CB001','HHK01','HV001',1005000,'TT001');
insert into VE values('VE102','CB001','HHK01','HV002',1000000,'TT002');
insert into VE values('VE103','CB001','HHK01','HV001',1050000,'TT000');
insert into VE values('VE201','CB002','HHK03','HV001',2100000,'TT000');
insert into VE values('VE202','CB002','HHK03','HV001',2100000,'TT001');
insert into VE values('VE203','CB002','HHK03','HV002',2000000,'TT002');
insert into VE values('VE301','CB003','HHK04','HV002',1500000,'TT001');
insert into VE values('VE302','CB003','HHK04','HV001',1575000,'TT002');

>>>>>>> dd28de0e5348ba65d5fabec9eb21e8519f5a1573
CREATE PROCEDURE TaoThanhVien
	@MaKH char(5),
	@HoTen NVARCHAR(50),
	@Tuoi INT,
	@GioiTinh BIT,
	@CMND CHAR(15),
	@DiaChi NVARCHAR(50),
	@SDT CHAR(15)
AS
BEGIN
	INSERT INTO KHACHHANG(MaKH, HoTen,Tuoi,GioiTinh,CMND,DiaChi, SDT)
	VALUES (@MaKH, @HoTen,@Tuoi,@GioiTinh,@CMND,@DiaChi, @SDT);
END


-------- Procedure Chuyen bay ---------
CREATE PROCEDURE LietKeCB
AS
BEGIN
	SELECT distinct CB.MACB, A.[SÂN BAY ĐI] AS 'SÂN BAY ĐI', B.[SÂN BAY ĐẾN] AS 'SÂN BAY ĐẾN', 
		HHK.TENHHK AS 'HÃNG HÀNG KHÔNG', THOIGIANKHOIHANH AS'THỜI GIAN KHỞI HÀNH', THOIGIANDEN AS 'THỜI GIAN ĐẾN', 
		CB.SOGHEHANG1 AS 'SỐ GHẾ HẠNG 1', CB.SOGHEHANG2 AS'SỐ GHẾ HẠNG 2', CB.GIAVE AS'GIÁ VÉ'
	FROM 
	(SELECT CB.MASBDI, SB.TENSANBAY AS 'SÂN BAY ĐI' FROM 
			SANBAY SB INNER JOIN CHUYENBAY CB ON CB.MASBDI = SB.MASB) AS A
	INNER JOIN 	CHUYENBAY CB ON A.MASBDI = CB.MASBDI INNER JOIN
	(SELECT CB.MASBDEN, SB.TENSANBAY AS'SÂN BAY ĐẾN' FROM SANBAY SB 
	INNER JOIN CHUYENBAY CB ON CB.MASBDEN = SB.MASB) AS B ON CB.MASBDEN = B.MASBDEN
	INNER JOIN HANGHK HHK ON CB.MAHHK = HHK.MAHHK
END

--------

CREATE PROCEDURE ThemCB
	@MaCB char(5),
	@TenSBDi nvarCHAR(30),
	@TenSBDen nvarCHAR(30),
	@TenHHK nvarCHAR(30),
	@ThoiGianKhoiHanh SMALLDATETIME,
	@ThoiGianDen SMALLDATETIME,
	@SoGheHang1 INT,
	@SoGheHang2 INT,
	@GiaVe INT
AS
BEGIN
	INSERT INTO CHUYENBAY(MACB, MASBDI, MASBDEN, MAHHK, THOIGIANKHOIHANH,THOIGIANDEN, SOGHEHANG1, SOGHEHANG2, GIAVE)
	VALUES (@MaCB,
	(SELECT MASB FROM SANBAY WHERE TENSANBAY = @TenSBDi),
	(SELECT MASB FROM SANBAY WHERE TENSANBAY = @TenSBDen),
	(SELECT MAHHK FROM HANGHK WHERE TENHHK = @TenHHK),
	@ThoiGianKhoiHanh, @ThoiGianDen, @SoGheHang1, @SoGheHang2, @GiaVe)
END

-----

CREATE PROCEDURE SuaCB
	@MaCB char(5),
	@TenSBDi nvarCHAR(30),
	@TenSBDen nvarCHAR(30),
	@TenHHK nvarCHAR(30),
	@ThoiGianKhoiHanh SMALLDATETIME,
	@ThoiGianDen SMALLDATETIME,
	@SoGheHang1 INT,
	@SoGheHang2 INT,
	@GiaVe INT
AS
BEGIN
	UPDATE CHUYENBAY
	SET
	MaSBDi = (SELECT MASB FROM SANBAY WHERE TENSANBAY = @TenSBDi),
	MASBDEN = (SELECT MASB FROM SANBAY WHERE TENSANBAY = @TenSBDen),
	MAHHK = (SELECT MAHHK FROM HANGHK WHERE TENHHK = @TenHHK),
	THOIGIANKHOIHANH = @ThoiGianKhoiHanh,
	THOIGIANDEN = @ThoiGianDen,
	SOGHEHANG1 = @SoGheHang1,
	SOGHEHANG2 = @SoGheHang2,
	GIAVE = @GiaVe
	WHERE MACB = @MaCB;
END

------

CREATE PROCEDURE XoaCB
	@MaCB char(5)
AS
BEGIN
	DELETE FROM CHUYENBAY WHERE MACB = @MaCB;
END

------

CREATE PROCEDURE TraCuu
	@MaSBDi nvarchar(40),
	@MaSBDen nvarchar(40),
	@ThoiGianBay datetime
AS
BEGIN
	SELECT distinct CB.MACB, A.[SÂN BAY ĐI] AS 'SÂN BAY ĐI', B.[SÂN BAY ĐẾN] AS 'SÂN BAY ĐẾN', 
		HHK.TENHHK AS 'HÃNG HÀNG KHÔNG', THOIGIANKHOIHANH AS'THỜI GIAN KHỞI HÀNH', THOIGIANDEN AS 'THỜI GIAN ĐẾN', 
		CB.SOGHEHANG1 AS 'SỐ GHẾ HẠNG 1', CB.SOGHEHANG2 AS'SỐ GHẾ HẠNG 2', CB.GIAVE AS'GIÁ VÉ'
	FROM 
	(SELECT CB.MASBDI, SB.TENSANBAY AS'SÂN BAY ĐI' FROM 
			SANBAY SB INNER JOIN CHUYENBAY CB ON CB.MASBDI = SB.MASB) AS A
	INNER JOIN 	CHUYENBAY CB ON A.MASBDI = CB.MASBDI INNER JOIN
	(SELECT CB.MASBDEN, SB.TENSANBAY AS'SÂN BAY ĐẾN' FROM SANBAY SB 
	INNER JOIN CHUYENBAY CB ON CB.MASBDEN = SB.MASB) AS B ON CB.MASBDEN = B.MASBDEN
	INNER JOIN HANGHK HHK ON CB.MAHHK = HHK.MAHHK
WHERE a.[SÂN BAY ĐI] = @MaSBDi AND b.[SÂN BAY ĐẾN] = @MaSBDen AND 
		convert (date, CB.THOIGIANKHOIHANH) = @ThoiGianBay
END


------------- Procedure Ve -----------
CREATE PROCEDURE UpdateTinhTrangVe
	@MaTT char(5),
	@MaVe char(5)
AS
BEGIN
	UPDATE VE
	SET MATT = @MaTT
	WHERE MAVE = @MaVe
END

------

CREATE PROCEDURE LietKeVe
	@MaCB char(5)
AS
BEGIN
	SELECT DISTINCT VE.MAVE, VE.MACB, HHK.TENHHK AS 'HÃNG HÀNG KHÔNG', HV.TENHANGVE AS 'HẠNG VÉ',
	VE.GIATIEN AS 'GIÁ TIỀN', TT.TENTINHTRANG AS 'TÌNH TRẠNG'
	FROM VE INNER JOIN HANGHK HHK ON VE.MAHHK = HHK.MAHHK
	INNER JOIN TINHTRANG TT ON VE.MATT = TT.MATT
	INNER JOIN HANGVE HV ON HV.MAHV = VE.MAHV
	WHERE VE.MACB = @MaCB
END

CREATE PROCEDURE ChonHangVe
	@TenHangVe nvarchar(8),
	@MaCB char(5)
AS
BEGIN
	SELECT DISTINCT VE.MAVE, VE.MACB,HHK.TENHHK AS 'HÃNG HÀNG KHÔNG', HV.TENHANGVE AS 'HẠNG VÉ',
	VE.GIATIEN AS 'GIÁ TIỀN', TT.TENTINHTRANG AS 'TÌNH TRẠNG'
	FROM VE INNER JOIN HANGHK HHK ON VE.MAHHK = HHK.MAHHK
	INNER JOIN TINHTRANG TT ON VE.MATT = TT.MATT
	INNER JOIN HANGVE HV ON HV.MAHV = VE.MAHV
	WHERE HV.TENHANGVE = @TenHangVe and VE.MACB = @MaCB
END

------

CREATE PROCEDURE LoadVe
	@MaCB char(5) =null,
	@MaVe char(5) =null
AS
BEGIN
	SELECT VE.MAVE, VE.MACB, VE.GIATIEN AS 'GIÁ VÉ', TT.TENTINHTRANG AS 'TÌNH TRẠNG', PDM.DATHANHTOAN AS'THANH TOÁN'
	FROM VE INNER JOIN TINHTRANG TT ON VE.MATT = TT.MATT
	INNER JOIN PHIEUDATMUA PDM ON VE.MAVE = PDM.MAVE
	WHERE VE.MACB = @MaCB OR VE.MAVE = @MaVe
END


-------------- Procedure San bay -------------
CREATE PROCEDURE LoadSanBay
	@MaSB char(5)
AS
BEGIN
	SELECT TENSANBAY
	FROM SANBAY 
	WHERE MASB = @MaSB
END

-------- Procedure Phieu dat mua ---------
CREATE PROCEDURE TaoPhieuDatMua	
	@MaVe CHAR(5),
	@MaKH CHAR(5),
	@ThoiGianDat SMALLDATETIME,
	@DaThanhToan bit
AS
BEGIN
	INSERT INTO PHIEUDATMUA
	VALUES (@MaVe, @MaKH, @ThoiGianDat, @DaThanhToan)
END



--------- Procedure Bao cao -----------
CREATE PROCEDURE BaoCao
	@TuNgay smalldatetime,
	@DenNgay smalldatetime
AS
BEGIN
	SELECT DISTINCT A.MACB,A.[ĐÃ BÁN], A.[DOANH THU], ROUND(A.[ĐÃ BÁN]*1.0/B.[TỔNG SỐ],2) AS'TỈ LỆ'
	FROM 
		(SELECT VE.MACB, COUNT(VE.MAVE) AS'ĐÃ BÁN', SUM(VE.GIATIEN) AS 'DOANH THU'
			FROM VE 
			INNER JOIN PHIEUDATMUA PDM ON VE.MAVE = PDM.MAVE
			WHERE VE.MATT='TT001'
			GROUP BY VE.MACB) AS A 
		INNER JOIN 
			(SELECT VE.MACB, COUNT(VE.MAVE) AS 'TỔNG SỐ'
			FROM VE
			GROUP BY VE.MACB) AS B
		ON A.MACB = B.MACB
		INNER JOIN VE ON A.MACB = VE.MACB
		INNER JOIN PHIEUDATMUA PDM ON VE.MAVE=PDM.MAVE
	WHERE VE.MATT='TT001' AND CONVERT(DATE, PDM.THOIGIANDAT) >= @TuNgay 
		AND CONVERT(DATE, PDM.THOIGIANDAT) <= @DenNgay
END

-------

CREATE PROCEDURE BaoCaoNam
	@NAM INT
AS
BEGIN
	SELECT DISTINCT A.MACB,A.[ĐÃ BÁN], A.[DOANH THU], ROUND(A.[ĐÃ BÁN]*1.0/B.[TỔNG SỐ],2) AS'TỈ LỆ'
	FROM 
		(SELECT VE.MACB, COUNT(VE.MAVE) AS'ĐÃ BÁN', SUM(VE.GIATIEN) AS 'DOANH THU'
			FROM VE 
			INNER JOIN PHIEUDATMUA PDM ON VE.MAVE = PDM.MAVE
			WHERE VE.MATT='TT001'
			GROUP BY VE.MACB) AS A 
		INNER JOIN 
			(SELECT VE.MACB, COUNT(VE.MAVE) AS 'TỔNG SỐ'
			FROM VE
			GROUP BY VE.MACB) AS B
		ON A.MACB = B.MACB
		INNER JOIN VE ON A.MACB = VE.MACB
		INNER JOIN PHIEUDATMUA PDM ON VE.MAVE=PDM.MAVE
	WHERE VE.MATT='TT001' AND DATEPART(YEAR, PDM.THOIGIANDAT) = @NAM
END

<<<<<<< HEAD

=======
CREATE PROCEDURE LoadVe
	@MaCB char(5) =null,
	@MaVe char(5) =null
AS
BEGIN
	SELECT VE.MAVE, VE.MACB, VE.GIATIEN AS 'GIÁ VÉ', TT.TENTINHTRANG AS 'TÌNH TRẠNG', PDM.DATHANHTOAN AS'THANH TOÁN'
	FROM VE INNER JOIN TINHTRANG TT ON VE.MATT = TT.MATT
	INNER JOIN PHIEUDATMUA PDM ON VE.MAVE = PDM.MAVE
	WHERE VE.MACB = @MaCB OR VE.MAVE = @MaVe
END

CREATE PROCEDURE ThanhToan
	@MaVe char(5)
AS
BEGIN
	UPDATE PHIEUDATMUA
	SET DATHANHTOAN ='1'
	WHERE MAVE = @MaVe
	UPDATE VE
	SET MATT ='TT001'
	WHERE MAVE= @MaVe
END

CREATE PROCEDURE HoanVe
	@MaVe char(5)
AS
BEGIN 
	UPDATE PHIEUDATMUA
	SET DATHANHTOAN = '0'
	WHERE MAVE = @MaVe
	UPDATE VE
	SET MATT = 'TT000'
	WHERE MAVE = @MaVe
END
>>>>>>> dd28de0e5348ba65d5fabec9eb21e8519f5a1573
